export enum Sprite {
  Archer = 'archer',
  Arrow = 'arrow',
  Background = 'background',
  Beachball = 'beachball',
  Blackrock = 'blackrock',
  Goblin = 'goblin',
  Guard = 'guard',
  Island = 'island',
  Menu = 'menu',
  Orc = 'orc',
  Particle = 'particle',
  Shore = 'shore',
  Slime = 'slime',
  Witch = 'witch',
  Yellowstone = 'yellowstone',
}
